[general]
import = ["/home/michael/.config/alacritty/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[terminal.shell]
args = ["-l"]
program = "/bin/bash"

[window]
startup_mode = "Maximized"

[font]
size = 12

[font.bold]
family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaCove Nerd Font"
style = "Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[keyboard]
bindings = [
  { key = "Enter", mods = "Alt", action = "ToggleFullscreen" },
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
  { key = "Enter", mods = "Control|Shift", action = "Open" },
  { key = "W", mods = "Control|Shift", action = "Quit" },
]
